apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: write-to-s3-task
spec:
  params:
    - name: AWS_REGION
      default: 'us-east-2'
      type: string
    - name: AWS_S3_BUCKET
      default: 'konflux-logs'
      type: string
    - name: DESTINATION_PATH
      default: 'logs/artifacts'
      type: string
  volumes:
    - name: secret-volume
      secret:
        secretName: aws-creds
  steps:
    - name: write-to-bucket
      image: amazon/aws-cli
      script: |
        #!/bin/sh
        
        # Configure AWS creds       
        aws configure set aws_access_key_id $(cat /workspace/AWS_ACCESS_KEY_ID)
        aws configure set aws_secret_access_key $(cat /workspace/AWS_SECRET_ACCESS_KEY)
        aws configure set region $(inputs.params.AWS_REGION)

        # Assume role and interact with new temp creds
        aws sts assume-role --role-arn $(cat /workspace/AWS_ROLE_ARN) --role-session-name tekton-s3-write-task --output json > tmp_credentials.json
        
        # Extract and export the new temp session creds
        yum install -y jq

        aws configure set aws_access_key_id $(jq -r '.Credentials.AccessKeyId' tmp_credentials.json)
        aws configure set aws_secret_access_key $(jq -r '.Credentials.SecretAccessKey' tmp_credentials.json)
        aws configure set aws_session_token $(jq -r '.Credentials.SessionToken' tmp_credentials.json)

        # Create sample XML for testing file write
        echo '<?xml version="1.0" encoding="UTF-8"?>
        <testsuites>
          <testsuite name="SampleTestSuite" tests="1" failures="0" errors="0" time="0.123">
            <testcase name="SampleTestCase" classname="SampleTestClass" time="0.123"/>
          </testsuite>
        </testsuites>' > test_report.xml

        # Write XML data to bucket creating a unique dir using taskRun.name
        aws s3 cp test_report.xml s3://$(inputs.params.AWS_S3_BUCKET)/$(inputs.params.DESTINATION_PATH)/$(context.pipelineRun.name)/$(context.pipelineRun.uid)/ --region $(inputs.params.AWS_REGION)

      volumeMounts:
        - name: secret-volume
          mountPath: /workspace

