apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: write-to-s3-pipeline
spec:
  tasks:
    - name: write-to-s3-task
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/ascerra/rhtap-e2e
          - name: revision
            value: bucket-testing
          - name: pathInRepo
            value: integration/write-to-s3-task.yaml
